### ISSUE TITLE
Game exits when launcher is closed

### ISSUE THREAD

**Issue by shelltitan** [griefly/griefly#257]
If you open one game window and launcher, and you close your launcher game closes it self too.(Is it here to prevent multiple connections from same computer?)

**Comment by kremius** [comment]
It is an intentional behaviour. It should prevent accidental, reconnects for users. Moreover, if you will try to close launcher when the game window is still running then the launcher should show warning about that.
If it is needed to perform multiple connections from one machine then it is needed to run the game executable with command line params (basically, the launcher do the same).

**Comment by mechmind** [comment]
If you want to start game without launcher consult https://github.com/griefly/griefly#how-to-run-game-without-launcher
