### ISSUE TITLE
More coverage, better task list

### ISSUE THREAD

**Issue by shelltitan** [griefly/griefly#286]
I have been reading ss13 reddit (https://www.reddit.com/r/SS13/) and this source hasn't been mentioned since your first open test, I thought giving some publicity to the source could help the progress. Other thing is that the issues' list is bit long and might be bit misleading lot of the issues isn't priority issues so maybe promoting the milestone issue would be a good thing(using git or other site like https://trello.com/ ).

**Comment by kremius** [comment]
https://github.com/griefly/griefly/milestone/5 here is the list of the current milestone issues. It is quite small list, so I think it is convenient enough.
I am not good at advertising, so I do it when it is needed (for example, when it is needed to conduct a beta-test). Current state of Griefly is really boring, only that can be said that "it is needed to make a lot of things, and we can show only some primitive gameplay". When 0.4 will be ready I may post something on SS13-related sites, but not now. However, Griefly is open-source project, so anyone can post anything about it anywhere he likes.
For the future: do not place more than one issue in one issue-post, split it

**Comment by shelltitan** [comment]
Well I get that but like ss14 and ss13 3d (or something like that) is often mentioned by people but griefly was mentioned one time, so I just say that the programmers that would/could help this project don't have an easy job as with ss14.

**Comment by kremius** [comment]
Well for some reason people do not talk about Griefly. I do not know what can be done with that. Griefly is not flashy remake with new cool graphics, it just plain old SS13, but on the new engine. People tends to evaluate graphics much more than engine things (obviously because they can easily see visual stuff, but it is needed to be a programmer and spend some time in order to understand internal things).
