### ISSUE TITLE
Sudden crash during the game process if dmi parsing is failed

### ISSUE THREAD

**Issue by shelltitan** [griefly/griefly#374]
If you spawn as security and move to right from the starting room to the room filled with 6 tables, you get a crash.

**Comment by shelltitan** [comment]
There is a fail in loading from items.dmi.

**Comment by shelltitan** [comment]
There are more spots where the client crashes as I try to move there.

**Comment by kremius** [comment]
Are you using your branch version or the master branch version? Everything works fine for me on the master branch. Note that the current map is `gloom.gen.txt` in the `maps` folder.

**Comment by shelltitan** [comment]
I used my upgrade but I didn't add anything to map yet just using yours.

**Comment by kremius** [comment]
Then try to reproduce issue with the master branch. There is a possibility that the pull requests introduces some bugs -> it is needed to try without changes.

**Comment by shelltitan** [comment]
Though the temperature indicator is bugged it somehow gets to the freezing temp 2nd state so it switching between the green and the blue state.

**Comment by shelltitan** [comment]
I don't happens on griefly-main branch version.

**Comment by shelltitan** [comment]
Maybe because the new variable on floors, I cannot guess anything from logs, the error is segmentation fault.

**Comment by kremius** [comment]
I have reproduced the issue on your branch.
You have changed `items.dmi` file -> that the source of the error. Seems like some states are missing, or something like that and that cause the crash. I have changed the file back and everything started work again.
It is still bug because the game should not crash if state is missing -> I will look into it.
On your branch you should not change `items.dmi` file (not sure why it was changed anyway - the current `items.dmi` file has medicine sprites, and you are using `item.dmi` file in the `Medicine` class).

**Comment by shelltitan** [comment]
I will revert that then.

**Comment by shelltitan** [comment]
If you launch the editor you won't get a crash so it was weird for me that I didn't saw anything common between crash sites that couldn't be found anywhere else where you don't crash.

**Comment by kremius** [comment]
So overall the chain of events that causes the bug:
1. The dmi parser starts to parse `items.dmi` metadata
2. It reads the file just fine until the `"bola_r"` state description
```
state = "bola_r"
	dirs = 4
	frames = 4
	delay = 0.5,0.5,0.5,0.5
	movement = 1

```
3. The parser tries to parse it and fails miserably. It happens because the parser thinks that `delay` values are integer, but actually they are float/double.
```
New state:  "\"bola_r\""
Fail to read ',' from .dmi file
End load metadata for  "icons/items.dmi"
Fail metadata load, try without it
```
4. When parser fails to load metadata it uses the fallback option - it tries to load it without metadata.
5. Unfortunately, `InitWithoutMetadata()` does not remove already parsed states (for example, in our case `sheet-metal` state is parsed just fine, so it is placed to `metadata_` map variable in `ImageMetadata` class).
6. Unfortunately x2, `SpriteMetadata` objects should have valid `frames_sequence` array. Usually, all `frames_sequence`s are initialized in the `MakeSequence()` call for each state. But this call happens only once in the end of the `ParseDescription()` function - so sequences are generated at once for all states.
7. If there is an error during parsing then `MakeSequence()` function will not be called -> that means that we will get a plenty of half-initialized states (i.e. they have name, start point and etc, but `frames_sequence` size is 0).
8. During `View2::FramesetState::Draw` call next line is reached, but `frames_sequence` is empty, so `operator[]` call causes the crash.
```
int current_frame = GetMetadata()->frames_sequence[image_state_];
```
9. Map editor does not crash because it does not use `frame_sequence` (and ignores animated sprites accordingly) - it just takes the first frame of the sprite (which can consist of several images, because a frame may have multiple directions). For that the editor uses `first_frame_pos_`, `width_` and `height_` values - and they are loaded correctly.

Сonclusion:
1. Delay should be `float` instead of `quint32` and parsing & drawing should be fixed.
2. `InitWithoutMetadata` should reset a `ImageMetadata` object to the initial state.
3. If a metadata parse error happens then the parser should crash immediately with message & `KvAbort()` and not hide the issue.
4. Also seems like dmi metadata can have multiple description with same names (e.g. `bola_r` has two descriptions in the `items.dmi` file). Investigation is needed.

**Comment by kremius** [comment]
Troublesome `items.dmi` file
![items](https://cloud.githubusercontent.com/assets/3407912/21788478/58a43864-d6e8-11e6-9062-3ea42df0170f.png)
